#!/bin/sh
MY_JAVA=$(java-config -J)
MY_CP="."
#MY_CP="${MY_CP}:$(java-config -p tos-simdriver-1)"
#MY_CP="${MY_CP}:$(java-config -p tos-sim-msg-1)"
#MY_CP="${MY_CP}:$(java-config -p tos-util-1)"
#MY_CP="${MY_CP}:$(java-config -p tos-message-1)"
#MY_CP="${MY_CP}:$(java-config -p tos-tython-1)"
#MY_CP="${MY_CP}:$(java-config -p tos-sf-1)"
#MY_CP="${MY_CP}:$(java-config -p tos-packet-1)"
#MY_CP="${MY_CP}:$(java-config -p oalnf)"
MAIN=net.tinyos.tools.Listen
exec ${MY_JAVA} -classpath ${MY_CP} ${MY_ARGS}   -class ${MAIN} "${@}"

