#!/bin/sh

MY_JAVA=$(java-config -J)
MY_CP="."
MY_CP="${MY_CP}:$(java-config -p tos-util)"
MY_CP="${MY_CP}:$(java-config -p tos-message)"
MY_CP="${MY_CP}:$(java-config -p tos-packet)"
MY_CP="${MY_CP}:$(java-config -p tos-bcastinject)"
#echo ${MY_JAVA} -jar -classpath ${MY_CP} ${MY_ARGS} ${MY_JAR} "${@}"
exec ${MY_JAVA} -classpath ${MY_CP} ${MY_ARGS} ${MY_JAR} net.tinyos.tools.BcastInject   "${@}"
