#!/bin/sh
MY_JAVA=$(java-config -J)
MY_JAR=$(java-config -p tos-simdriver)
MY_ARGS="-Dpython.cachedir=/tmp/jython.cache -DDBG=$DBG -DSIMDBG=$SIMDBG"
MY_CP="."
MY_CP="."
MY_CP="${MY_CP}:$(java-config -p tos-simdriver)"
MY_CP="${MY_CP}:$(java-config -p tos-sim-msg)"
MY_CP="${MY_CP}:$(java-config -p tos-util)"
MY_CP="${MY_CP}:$(java-config -p tos-message)"
MY_CP="${MY_CP}:$(java-config -p tos-tython)"
MY_CP="${MY_CP}:$(java-config -p tos-sf)"
MY_CP="${MY_CP}:$(java-config -p tos-packet)"
MY_CP="${MY_CP}:$(java-config -p oalnf)"
#echo ${MY_JAVA} -jar -classpath ${MY_CP} ${MY_ARGS} ${MY_JAR} "${@}"
exec ${MY_JAVA} -jar -classpath ${MYCP} ${MY_ARGS} ${MY_JAR} "${@}"
