#!/bin/sh
MY_JAVA=$(java-config -J)
MY_JAR=$(java-config -p tos-simdriver)
MY_ARGS="-Dpython.cachedir=/tmp/jython.cache -DDBG=$DBG -DSIMDBG=$SIMDBG"
MY_CP="."
MY_CP="${MY_CP}:$(java-config -p tos-simdriver)"
MY_CP="${MY_CP}:$(java-config -p tos-sim-msg)"
MY_CP="${MY_CP}:$(java-config -p tos-util)"
MY_CP="${MY_CP}:$(java-config -p tos-message)"
MY_CP="${MY_CP}:$(java-config -p tos-tython)"
MY_CP="${MY_CP}:$(java-config -p tos-sf)"
MY_CP="${MY_CP}:$(java-config -p tos-packet)"
MY_CP="${MY_CP}:$(java-config -p oalnf)"
MY_CP="${MY_CP}:$(java-config -p ptplot)"
MY_CP="${MY_CP}:$(java-config -p jama)"
MY_CP="${MY_CP}:$(java-config -p log4j)"
MY_CP="${MY_CP}:$(java-config -p xmlrpc)"
MY_CP="${MY_CP}:$(java-config -p jdom-1.0)"
MY_CP="${MY_CP}:$(java-config -p servletapi-2.3)"



#echo ${MY_JAVA} -jar -classpath ${MY_CP} ${MY_ARGS} ${MY_JAR} -gui "${@}"
exec ${MY_JAVA} -jar -classpath ${MY_CP} ${MY_ARGS} ${MY_JAR} -gui "${@}"

