#!/bin/sh
MY_JAVA=$(java-config -J)
MY_CP="."
MY_CP="${MY_CP}:$(java-config -p tos-simdriver)"
MY_CP="${MY_CP}:$(java-config -p tos-sim-msg)"
MY_CP="${MY_CP}:$(java-config -p tos-util)"
MY_CP="${MY_CP}:$(java-config -p tos-message)"
MY_CP="${MY_CP}:$(java-config -p tos-tython)"
MY_CP="${MY_CP}:$(java-config -p tos-sf)"
MY_CP="${MY_CP}:$(java-config -p tos-packet)"
MY_CP="${MY_CP}:$(java-config -p oalnf)"
MAIN=net.tinyos.sf.SerialForwarder
#echo ${MY_JAVA} -classpath ${MY_CP} ${MY_ARGS}  -class ${MAIN} "${@}"
exec ${MY_JAVA} -classpath ${MY_CP} ${MY_ARGS}  -class ${MAIN} "${@}"

